name: basic
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - pandas ==1.2.4
  - xarray ==0.15.1
  - xesmf ==0.3.0
  - natsort ==7.0.1
  # Jupyter and JupyterHub dependencies
  - bash_kernel ==0.7.2
  - jupyter ==1.0.0 
  - jupyterhub ==1.5.0
  - notebook ==6.4.2
  - jupyterlab ==3.1.17
  - jupyter_nbextensions_configurator ==0.4.1
  - rise ==5.7.1
  # required to decouple binder and repo
  - nbgitpuller ==1.0.2
  # optional jupyter labextensions (i.e. git) build dependencies
  - jupyterlab-git ==0.33.0
  - nodejs ==15.14.0
  - pip ==21.2.4
  - wheel ==0.37.0
  # Other
  - gh ==2.2.0
