name: pyclimenv
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - cartopy #==0.20.2
  - dask #==2022.2.0
  - doi2bib #==0.4.0
  - esgf-pyclient #==0.3.1
  - natsort #==8.0.1
  - netCDF4
  - pandas #==1.3.5
  - seaborn #==0.11.2
  - xarray #==0.20.2
  - xesmf #==0.6.2
  # Jupyter dependencies
  - bash_kernel #==0.7.2
  # required to decouple binder and repo
  - nbgitpuller #==1.1.0
  # optional jupyterlab extensions (i.e. git) build dependencies
  - jupyterlab-git #==0.37.1
  - nodejs #==17.9.0
  - wheel #==0.37.1
  # Other
  - cdo #==2.0.3
  - nco #==5.0.7
  - gh #==2.11.3
